require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntryTypesController do

  # This should return the minimal set of attributes required to create a valid
  # EntryType. As you add validations to EntryType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EntryTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all entry_types as @entry_types" do
      entry_type = EntryType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:entry_types).should eq([entry_type])
    end
  end

  describe "GET show" do
    it "assigns the requested entry_type as @entry_type" do
      entry_type = EntryType.create! valid_attributes
      get :show, {:id => entry_type.to_param}, valid_session
      assigns(:entry_type).should eq(entry_type)
    end
  end

  describe "GET new" do
    it "assigns a new entry_type as @entry_type" do
      get :new, {}, valid_session
      assigns(:entry_type).should be_a_new(EntryType)
    end
  end

  describe "GET edit" do
    it "assigns the requested entry_type as @entry_type" do
      entry_type = EntryType.create! valid_attributes
      get :edit, {:id => entry_type.to_param}, valid_session
      assigns(:entry_type).should eq(entry_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EntryType" do
        expect {
          post :create, {:entry_type => valid_attributes}, valid_session
        }.to change(EntryType, :count).by(1)
      end

      it "assigns a newly created entry_type as @entry_type" do
        post :create, {:entry_type => valid_attributes}, valid_session
        assigns(:entry_type).should be_a(EntryType)
        assigns(:entry_type).should be_persisted
      end

      it "redirects to the created entry_type" do
        post :create, {:entry_type => valid_attributes}, valid_session
        response.should redirect_to(EntryType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entry_type as @entry_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntryType.any_instance.stub(:save).and_return(false)
        post :create, {:entry_type => { "name" => "invalid value" }}, valid_session
        assigns(:entry_type).should be_a_new(EntryType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntryType.any_instance.stub(:save).and_return(false)
        post :create, {:entry_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entry_type" do
        entry_type = EntryType.create! valid_attributes
        # Assuming there are no other entry_types in the database, this
        # specifies that the EntryType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EntryType.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => entry_type.to_param, :entry_type => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested entry_type as @entry_type" do
        entry_type = EntryType.create! valid_attributes
        put :update, {:id => entry_type.to_param, :entry_type => valid_attributes}, valid_session
        assigns(:entry_type).should eq(entry_type)
      end

      it "redirects to the entry_type" do
        entry_type = EntryType.create! valid_attributes
        put :update, {:id => entry_type.to_param, :entry_type => valid_attributes}, valid_session
        response.should redirect_to(entry_type)
      end
    end

    describe "with invalid params" do
      it "assigns the entry_type as @entry_type" do
        entry_type = EntryType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntryType.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_type.to_param, :entry_type => { "name" => "invalid value" }}, valid_session
        assigns(:entry_type).should eq(entry_type)
      end

      it "re-renders the 'edit' template" do
        entry_type = EntryType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntryType.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_type.to_param, :entry_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entry_type" do
      entry_type = EntryType.create! valid_attributes
      expect {
        delete :destroy, {:id => entry_type.to_param}, valid_session
      }.to change(EntryType, :count).by(-1)
    end

    it "redirects to the entry_types list" do
      entry_type = EntryType.create! valid_attributes
      delete :destroy, {:id => entry_type.to_param}, valid_session
      response.should redirect_to(entry_types_url)
    end
  end

end
